
# https://assemble.io/docs/YAML-front-matter.html

theme: jekyll-theme-cayman


#theme: jekyll-theme-minimal

title: Comentário do COVID-19
description: Este site agrupa os meus comentários sobre o COVID-19 que publico no Facebook.
